<?php
return [
    "decimal_point"         => ",",
    "thousand_seperator"    => ".",
    "year"                  => "Jahr",
    "month"                 => "Monat",
    "week"                  => "Woche",
    "day"                   => "Tag",
    "hour"                  => "Stunde",
    "minute"                => "Minute",
    "second"                => "Sekunde",
    "time=1"                => "vor [number] [time]",
    "time>1"                => "vor [number] [time]en",

    "categories"            => "Kategorien",
    "filmanimation"         => "Film & Animation",
    "autovehicle"           => "Autos & Fahrzeuge",
    "music"                 => "Musik",
    "petsanimals"           => "Tiere",
    "sports"                => "Sport",
    "travelevents"          => "Reisen & Events",
    "gaming"                => "Spiele",
    "peopleblogs"           => "Leute & Blogs",
    "comedy"                => "Comedy",
    "entertainment"         => "Unterhaltung",
    "newspolitics"          => "Nachrichten & Politik",
    "howtostyle"            => "Tipps & Style",
    "education"             => "Bildung",
    "sciencetech"           => "Wissenschaft & Technologie",
    "nonprofit"             => "Gemeinnützigkeit",

    "h_home"      => "Startseite",
    "h_videos"    => "Videos",
    "h_channels"  => "Kanäle",
    "h_community" => "Gemeinschaft",
    "h_search"    => "Suchen",
    "h_signup"    => "Konto erstellen",
    "h_signin"    => "Anmelden",
    "h_or"        => "oder",
    "h_subs"      => "Abonnements",
    "h_history"   => "Protokoll",
    "h_upload"    => "Video hochladen",
    "w_watched"   => "Momentan angesehene Videos",
    "w_recommend" => "Empfohlen",
    "w_subscrib"  => "Abonnements",
    "w_featured"  => "Vorgestellte Videos",
    "w_popular"   => "Beliebteste Videos",
    "s_customize" => "Du möchtest diese Startseite anpassen?",
    "s_si_su"     => "Jetzt <a href='/signin'>anmelden</a> oder <a href='/signup'>registrieren</a>!",
    "contest"     => "Video-Wettbewerb",
    "contest_prm" => "Mache ein Video und teile es!",
    "contest_th"  => "Jetziges Thema:",
    "contest_ent" => "<a href='/upload?e=c'>Jetzt teilnehmen</a> | <a href='/contest'>Teilnahmen anschauen</a>",
    "view"        => "Aufruf",
    "views"       => "Aufrufe",
    "whatsnew"    => "Was gibt’s Neues",
    "delvid"      => "Gelöschtes Video",
    "prvvid"      => "Privates Video",
    "prtn"        => "Partner",
    "vrfd"        => "Verifiziert",
    "lastonline"  => "Letzte [num] Benutzer Online",
    "l_videos"    => "Videos",
    "l_favs"      => "Favoriten",
    "l_friends"   => "Freunde",
    "langs"       => "Sprachen",
    "lang"        => "Sprache",
    "vid_pl"      => "Video-Player",
    "layout"      => "Layout",
    "dark_mode"   => "Nachtmodus",
    "abtvid"      => "Über VidLii",
    "f_blg"       => "Blog",
    "f_about"     => "Über uns",
    "f_terms"     => "Bedingungen",
    "f_priv"      => "Datenschutz",
    "f_themes"    => "Themen",
    "hlp_inf"     => "Hilfe & Info",
    "f_hlp_cnt"   => "Hilfe-Center",
    "f_prtner"    => "Partnerschaft",
    "f_copy"      => "Kopierrecht",
    "f_comm"      => "Community-Richtlinien",
    "you_acc"     => "Dein Account",
    "f_vids"      => "Meine Videos",
    "f_favs"      => "Meine Favoriten",
    "f_subs"      => "Meine Abonnements",
    "f_acc"       => "Mein Account",
    "v_auto"      => "Video-Wiedergabe",
    "v_sauto"     => "Video automatisch starten",
    "v_cauto"     => "Video mit Klick starten",
    "v_size"      => "Video-Größe",
    "v_rsize"     => "Reguläre Video-Größe",
    "v_tsize"     => "Theater Video-Größe",
    "v_cust"      => "Player-Gestaltung",
    "v_butt"      => "Farbe Knöpfe",
    "v_back"      => "Hintergrund-Farbe",
    "save_change" => "Änderungen Speichern",

    "modules"     => "Module",
    "feed"        => "Feed",

    "modsettings" => "Wählen Sie aus, welche Module auf der Startseite auftauchen sollen",
    "m_mostview"  => "Meist gesehen",
    "m_inbox"     => "Inbox",
    "m_stats"     => "Kanal Statistiken",

    "subsettings" => "Abonnement Einstellungen",
    "s_num"       => "Anzahl der Reihen",
    "s_from"      => "Zeige Videos von",
    "s_everyone"  => "Jeden",

    "in"          => "in",
    "all_cats"    => "Allen Kategorien",
    "v_newest"    => "Neuste",
    "v_most_view" => "Meist Gesehen",
    "v_most_disc" => "Meist Diskutiert",
    "v_top_rate"  => "Best Bewertet",

    "no_videos"   => "Keine Videos wurden gefunden",

    "today"       => "Heute",
    "this_week"   => "Diese Woche",
    "this_month"  => "Dieser Monat",
    "all_time"    => "Immer",
];
