<?php
return [
    "decimal_point"         => ",",
    "thousand_seperator"    => ".",

    "h_home"      => "Startseite",
    "h_videos"    => "Videos",
    "h_channels"  => "Kanäle",
    "h_community" => "Gemeinschaft",
    "h_search"    => "Suchen",
    "h_signup"    => "Konto erstellen",
    "h_signin"    => "Anmelden",
    "h_or"        => "oder",
    "h_subs"      => "Abonnements",
    "h_history"   => "Protokoll",
    "h_upload"    => "Video hochladen",
    "w_watched"   => "Momentan angesehene Videos",
    "w_recommend" => "Empfohlen",
    "w_subscrib"  => "Abonnements",
    "w_featured"  => "Vorgestellte Videos",
    "w_popular"   => "Beliebteste Videos",
    "s_customize" => "Du möchtest diese Startseite anpassen?",
    "s_si_su"     => "Jetzt <a href='/signin'>anmelden</a> oder <a href='/signup'>registrieren</a>!",
    "contest"     => "Video Wettbewerb",
    "contest_prm" => "Mache ein Video und teile es!",
    "contest_th"  => "Jetziges Thema:",
    "contest_ent" => "<a href='/upload?e=c'>Jetzt teilnehmen</a> | <a href='/contest'>Teilnahmen anschauen</a>",
    "view"        => "Aufruf",
    "views"       => "Aufrufe",
    "whatsnew"    => "Was gibt's Neues",
    "delvid"      => "Gelöschtes Video",
    "prvvid"      => "Privates Video",
    "prtn"        => "Partner",
    "vrfd"        => "Verifiziert"
];