<?php
return [
    "decimal_point"         => ".",
    "thousand_seperator"    => ",",

    "h_home"      => "Home",
    "h_videos"    => "Videos",
    "h_channels"  => "Channels",
    "h_community" => "Community",
    "h_search"    => "Search",
    "h_signup"    => "Create Account",
    "h_signin"    => "Sign In",
    "h_or"        => "or",
    "h_subs"      => "Subscriptions",
    "h_history"   => "History",
    "h_upload"    => "Upload",
    "w_watched"   => "Videos Being Watched",
    "w_recommend" => "Recommended Videos",
    "w_subscrib"  => "Subscriptions",
    "w_featured"  => "Featured Videos",
    "w_popular"   => "Most Popular Videos",
    "s_customize" => "Want to customize this homepage?",
    "s_si_su"     => "<a href='/signin'>Sign In</a> or <a href='/signup'>Sign Up</a> now!",
    "contest"     => "Video Contest",
    "contest_prm" => "Make a video, upload it, share it!",
    "contest_th"  => "Current Theme:",
    "contest_ent" => "<a href='/upload?e=c'>Enter Now</a> | <a href='/contest'>View Entries</a>",
    "view"        => "view",
    "views"       => "views",
    "whatsnew"    => "What's New",
    "delvid"      => "Deleted Video",
    "prvvid"      => "Private Video",
    "prtn"        => "Partnered",
    "vrfd"        => "Verified"
];