<?php
return [
    "decimal_point"         => ".",
    "thousand_seperator"    => ",",
    "year"                  => "year",
    "month"                 => "month",
    "week"                  => "week",
    "day"                   => "day",
    "hour"                  => "hour",
    "minute"                => "minute",
    "second"                => "second",
    "time=1"                => "[number] [time] ago",
    "time>1"                => "[number] [time]s ago",

    "categories"            => "Categories",
    "filmanimation"         => "Film & Animation",
    "autovehicle"           => "Autos & Vehicles",
    "music"                 => "Music",
    "petsanimals"           => "Pets & Animals",
    "sports"                => "Sports",
    "travelevents"          => "Travel & Events",
    "gaming"                => "Gaming",
    "peopleblogs"           => "People & Blogs",
    "comedy"                => "Comedy",
    "entertainment"         => "Entertainment",
    "newspolitics"          => "News & Politics",
    "howtostyle"            => "Howto & Style",
    "education"             => "Education",
    "sciencetech"           => "Science & Technology",
    "nonprofit"             => "Nonprofits & Activism",

    "save_changes"          => "Save Changes",

    "h_home"      => "Home",
    "h_videos"    => "Videos",
    "h_channels"  => "Channels",
    "h_community" => "Community",
    "h_search"    => "Search",
    "h_signup"    => "Create Account",
    "h_signin"    => "Sign In",
    "h_or"        => "or",
    "h_subs"      => "Subscriptions",
    "h_history"   => "History",
    "h_upload"    => "Upload",
    "w_watched"   => "Videos Being Watched",
    "w_recommend" => "Recommended Videos",
    "w_subscrib"  => "Subscriptions",
    "w_featured"  => "Featured Videos",
    "w_popular"   => "Most Popular Videos",
    "s_customize" => "Want to customize this homepage?",
    "s_si_su"     => "<a href='/signin'>Sign In</a> or <a href='/signup'>Sign Up</a> now!",
    "contest"     => "Video Contest",
    "contest_prm" => "Make a video, upload it, share it!",
    "contest_th"  => "Current Theme:",
    "contest_ent" => "<a href='/upload?e=c'>Enter Now</a> | <a href='/contest'>View Entries</a>",
    "view"        => "view",
    "views"       => "views",
    "whatsnew"    => "What’s New",
    "delvid"      => "Deleted Video",
    "prvvid"      => "Private Video",
    "prtn"        => "Partnered",
    "vrfd"        => "Verified",
    "lastonline"  => "Last [num] Users Online",
    "l_videos"    => "videos",
    "l_favs"      => "favorites",
    "l_friends"   => "friends",
    "langs"       => "Languages",
    "lang"        => "Language",
    "vid_pl"      => "Video Player",
    "layout"      => "Layout",
    "dark_mode"   => "Dark Mode",
    "abtvid"      => "About VidLii",
    "f_blg"       => "Blog",
    "f_about"     => "About",
    "f_terms"     => "Terms of Use",
    "f_priv"      => "Privacy Policy",
    "f_themes"    => "Themes",
    "hlp_inf"     => "Help & Info",
    "f_hlp_cnt"   => "Help Center",
    "f_prtner"    => "Partnership",
    "f_copy"      => "Copyright",
    "f_comm"      => "Community Guidelines",
    "you_acc"     => "Your Account",
    "f_vids"      => "My Videos",
    "f_favs"      => "My Favorites",
    "f_subs"      => "My Subscriptions",
    "f_acc"       => "My Account",
    "v_auto"      => "Video Autoplay",
    "v_sauto"     => "Start Video Automatically",
    "v_cauto"     => "Start Video after clicking on it",
    "v_size"      => "Video Size",
    "v_rsize"     => "Regular Player Size",
    "v_tsize"     => "Theater Player Size",
    "v_cust"      => "Player Customization",
    "v_butt"      => "Buttons Color",
    "v_back"      => "Background Color",
    "save_change" => "Save Changes",

    "modules"     => "Modules",
    "feed"        => "Feed",

    "modsettings" => "Select the modules you want to appear on your homepage",
    "m_mostview"  => "Most Viewed",
    "m_inbox"     => "Inbox",
    "m_stats"     => "Channels Statistics",

    "subsettings" => "Subscription Settings",
    "s_num"       => "Number of Rows",
    "s_from"      => "Show videos from",
    "s_everyone"  => "Everyone",

    "in"          => "in",
    "all_cats"    => "All Categories",
    "v_newest"    => "Newest",
    "v_most_view" => "Most Viewed",
    "v_most_disc" => "Most Discussed",
    "v_top_rate"  => "Top Rated",

    "no_videos"   => "No videos were found",

    "today"       => "Today",
    "this_week"   => "This Week",
    "this_month"  => "This Month",
    "all_time"    => "All Time",
];
