<?php
return [
    "decimal_point"         => ",",
    "thousand_seperator"    => ".",

    "h_home"      => "Pagina Principal",
    "h_videos"    => "Videos",
    "h_channels"  => "Canales",
    "h_community" => "Comunidad",
    "h_search"    => "Buscar",
    "h_signup"    => "Registrate",
    "h_signin"    => "Inicia Sesión",
    "h_or"        => "o",
    "h_subs"      => "Suscripciones",
    "h_history"   => "Historial",
    "h_upload"    => "Subir",
    "w_watched"   => "Videos Siendo Vistos Ahora",
    "w_recommend" => "Videos recomendados",
    "w_subscrib"  => "Suscripciones",
    "w_featured"  => "Videos Destacados",
    "w_popular"   => "Mas Popular",
    "s_customize" => "Quieres Personalizar Tu Pagina Principal?",
    "s_si_su"     => "<a href='/signin'>Inicia Sesión</a> o <a href='/signup'>Registrate</a>!",
    "contest"     => "Concurso de video",
    "contest_prm" => "Haz un video, compártelo!",
    "contest_th"  => "Tema actual:",
    "contest_ent" => "<a href='/upload?e=c'>Entra Ahora</a> | <a href='/contest'>Ver Entradas</a>",
    "view"        => "ver",
    "views"       => "visitas",
    "whatsnew"    => "Novedades",
    "delvid"      => "Video eliminado",
    "prvvid"      => "Video privado",
    "prtn"        => "Compañero",
    "vrfd"        => "Verificado"
];
