<?php
return [
    "decimal_point"         => ".",
    "thousand_seperator"    => ",",

    "h_home"      => "Kezdőlap",
    "h_videos"    => "Videók",
    "h_channels"  => "Csatornák",
    "h_community" => "Közösség",
    "h_search"    => "Keresés",
    "h_signup"    => "Fiók létrehozása",
    "h_signin"    => "Bejelentkezés",
    "h_or"        => "vagy",
    "h_subs"      => "Feliratkozások",
    "h_history"   => "Előzmények",
    "h_upload"    => "Feltöltés",
    "w_watched"   => "Éppen nézett videók",
    "w_recommend" => "Neked ajánlott",
    "w_subscrib"  => "Feliratkozások",
    "w_featured"  => "Kiemelt videók",
    "w_popular"   => "Legnépszerübb",
    "s_customize" => "Testre szeretnéd szabni ezt az oldalt?",
    "s_si_su"     => "<a href='/signin'>Jelentkezz be</a> vagy <a href='/signup'>Regisztrálj</a> most!",
    "contest"     => "Videó verseny!",
    "contest_prm" => "Készits egy videót, töltsd fel, oszd meg!",
    "contest_th"  => "Téma:",
    "contest_ent" => "<a href='/upload?e=c'>Nevezz be</a> | <a href='/contest'>Nézd meg a benevezetteket</a>",
    "view"        => "megtekintés",
    "views"       => "megtekintés",
    "whatsnew"    => "Újdonságok",
    "delvid"      => "Törölt videó",
    "prvvid"      => "Privát videó",
    "prtn"        => "Partner",
    "vrfd"        => "Ellenőrizve"
];