<?php
return [
    "decimal_point"         => ".",
    "thousand_seperator"    => ",",
    "year"                  => "éve",
    "month"                 => "hónapja",
    "week"                  => "hete",
    "day"                   => "napja",
    "hour"                  => "órája",
    "minute"                => "perce",
    "second"                => "másodperce",
    "time=1"                => "[number] [time]",
    "time>1"                => "[number] [time]",

    "categories"            => "Kategóriák:",
    "filmanimation"         => "Film és animáció",
    "autovehicle"           => "Autók és más járművek",
    "music"                 => "Zene",
    "petsanimals"           => "Házi- és egyéb állatok",
    "sports"                => "Sport",
    "travelevents"          => "Utazás és események",
    "gaming"                => "Játék",
    "peopleblogs"           => "Emberek és blogok",
    "comedy"                => "Humor",
    "entertainment"         => "Szórakozás",
    "newspolitics"          => "Hírek és politika",
    "howtostyle"            => "Útmutatók és stílus",
    "education"             => "Oktatás",
    "sciencetech"           => "Tudomány és technika",
    "nonprofit"             => "Nonprofit szervezetek és aktivisták",

    "save_changes"          => "Beállitások mentése",

    "h_home"      => "Kezdőlap",
    "h_videos"    => "Videók",
    "h_channels"  => "Csatornák",
    "h_community" => "Közösség",
    "h_search"    => "Keresés",
    "h_signup"    => "Fiók létrehozása",
    "h_signin"    => "Bejelentkezés",
    "h_or"        => "vagy",
    "h_subs"      => "Feliratkozások",
    "h_history"   => "Előzmények",
    "h_upload"    => "Feltöltés",
    "w_watched"   => "Éppen nézett videók",
    "w_recommend" => "Neked ajánlott",
    "w_subscrib"  => "Feliratkozások",
    "w_featured"  => "Kiemelt videók",
    "w_popular"   => "Legnépszerübb",
    "s_customize" => "Testre szeretnéd szabni ezt az oldalt?",
    "s_si_su"     => "<a href='/signin'>Jelentkezz be</a> vagy <a href='/signup'>Regisztrálj</a> most!",
    "contest"     => "Videó verseny!",
    "contest_prm" => "Készits egy videót, töltsd fel, oszd meg!",
    "contest_th"  => "Téma:",
    "contest_ent" => "<a href='/upload?e=c'>Nevezz be</a> | <a href='/contest'>Nézd meg a benevezetteket</a>",
    "view"        => "megtekintés",
    "views"       => "megtekintés",
    "whatsnew"    => "Újdonságok",
    "delvid"      => "Törölt videó",
    "prvvid"      => "Privát videó",
    "prtn"        => "Partner",
    "vrfd"        => "Ellenőrizve",
    "lastonline"  => "Utolsó [num] felhasználó",
    "l_videos"    => "videók",
    "l_favs"      => "kedvencek",
    "l_friends"   => "barátok",
    "langs"       => "Nyelvek",
    "lang"        => "Nyelv",
    "vid_pl"      => "Videólejátszó",
    "layout"      => "Elrendezés",
    "dark_mode"   => "Éjszakai mód",
    "abtvid"      => "A VidLii-ről",
    "f_blg"       => "Blog",
    "f_about"     => "Rólunk",
    "f_terms"     => "Használati feltételek",
    "f_priv"      => "Adatvédelmi irányelvek",
    "f_themes"    => "Témák",
    "hlp_inf"     => "Súgó és információ",
    "f_hlp_cnt"   => "Segítség központ",
    "f_prtner"    => "Partnerség",
    "f_copy"      => "Szerzői jogok",
    "f_comm"      => "Közösségi irányelvek",
    "you_acc"     => "Saját fiók",
    "f_vids"      => "Saját videóim",
    "f_favs"      => "Saját kedvenceim",
    "f_subs"      => "Saját feliratkozásaim",
    "f_acc"       => "Saját fiókóm",
    "v_auto"      => "Videó lejátszása",
    "v_sauto"     => "Videó automatikus lejátszása",
    "v_cauto"     => "Videó indítása rákattintás után",
    "v_size"      => "Lejátszó mérete",
    "v_rsize"     => "Alapértelmezett nézet",
    "v_tsize"     => "Mozi nézet",
    "v_cust"      => "Lejátszó testreszabása",
    "v_butt"      => "Gombok színe",
    "v_back"      => "Háttérszín",
    "save_change" => "Beállitások mentése"

    "modules"     => "Modulok",
    "feed"        => "Hírcsatorna",

    "modsettings" => "Válaszd ki a modulokat amik megjelennek a kezdőlapon",
    "m_mostview"  => "Legnézettebb",
    "m_inbox"     => "Beérkező üzenetek",
    "m_stats"     => "Statisztika",

    "subsettings" => "Feliratkozások beállitása",
    "s_num"       => "Sorok száma",
    "s_from"      => "Mutasson videókat tőle",
    "s_everyone"  => "Mindenki",

    "in"          => "",
    "all_cats"    => "Minden kategóriában",
    "v_newest"    => "Legújabb",
    "v_most_view" => "Legnézettebb",
    "v_most_disc" => "Legvitatottabb",
    "v_top_rate"  => "Legjobban értékelt",

    "no_videos"   => "Nincs találat.",

    "today"       => "Ma",
    "this_week"   => "Ezen a héten",
    "this_month"  => "Ebben a hónapban",
    "all_time"    => "Mindig",
];
