<?php
return [
    "decimal_point"         => ".",
    "thousand_seperator"    => ",",
    "year"                  => "anno",
    "month"                 => "mese",
    "week"                  => "settimana",
    "day"                   => "giorno",
    "hour"                  => "ora",
    "minute"                => "minuto",
    "second"                => "secondo",
    "time=1"                => "[number] [time]",
    "time>1"                => "[number] [time]",

    "categories"            => "Categorie",
    "filmanimation"         => "Film & Animazione",
    "autovehicle"           => "Auto & Veicoli",
    "music"                 => "Musica",
    "petsanimals"           => "Animali",
    "sports"                => "Sport",
    "travelevents"          => "Viaggi & Eventi",
    "gaming"                => "Gaming",
    "peopleblogs"           => "Persone & Blogs",
    "comedy"                => "Commedia",
    "entertainment"         => "intrattenimento",
    "newspolitics"          => "Notizie & Politica",
    "howtostyle"            => "Come fare: & Stile di vita",
    "education"             => "Educazione",
    "sciencetech"           => "Scienza & Tecnologia",
    "nonprofit"             => "Nonprofits & Attivismo",

    "save_changes"          => "Salva modifiche",

    "h_home"      => "Home",
    "h_videos"    => "Video",
    "h_channels"  => "Canali",
    "h_community" => "Community",
    "h_search"    => "Cerca",
    "h_signup"    => "Crea un account",
    "h_signin"    => "Registrati",
    "h_or"        => "o",
    "h_subs"      => "Iscritti",
    "h_history"   => "Storia",
    "h_upload"    => "Carica",
    "w_watched"   => "Video guardati ora",
    "w_recommend" => "Video Consigliati",
    "w_subscrib"  => "Iscrizioni",
    "w_featured"  => "Video Consigliati",
    "w_popular"   => "I video più popolari",
    "s_customize" => "Vuoi modificare questa HomePage?",
    "s_si_su"     => "<a href='/signin'>Registrati</a> oppure <a href='/signup'>Crea un account</a> ora!",
    "contest"     => "Il Contest del mese",
    "contest_prm" => "Crea un video, caricalo!, condividilo!",
    "contest_th"  => "Tema attuale:",
    "contest_ent" => "<a href='/upload?e=c'>Entra ora!</a> | <a href='/contest'>Vedi i partecipanti</a>",
    "view"        => "visualizazione",
    "views"       => "visualizazioni",
    "whatsnew"    => "Cosa C'è di nuovo",
    "delvid"      => "Video eliminato",
    "prvvid"      => "Video privato",
    "prtn"        => "Partnered",
    "vrfd"        => "Verificato",
    "lastonline"  => "Gli ultimi [num] Utenti Online",
    "l_videos"    => "video",
    "l_favs"      => "Preferiti",
    "l_friends"   => "Amici",
    "langs"       => "Lingue",
    "lang"        => "Lingua",
    "vid_pl"      => "Video Player",
    "layout"      => "Layout",
    "dark_mode"   => "Modalità oscura",
    "abtvid"      => "Riguardo a VidLii",
    "f_blg"       => "Blog",
    "f_about"     => "Riguardo a noi",
    "f_terms"     => "Termini di uso",
    "f_priv"      => "Privacy Policy",
    "f_themes"    => "Temi",
    "hlp_inf"     => "Aiuto & Info",
    "f_hlp_cnt"   => "Centro di aiuto",
    "f_prtner"    => "Partnership",
    "f_copy"      => "Copyright",
    "f_comm"      => "Linee di Guida della Community",
    "you_acc"     => "Il tuo Account",
    "f_vids"      => "I miei Video",
    "f_favs"      => "I miei preferiti",
    "f_subs"      => "Le mie iscrizioni",
    "f_acc"       => "Il mio account",
    "v_auto"      => "Video Autoplay",
    "v_sauto"     => "Inizia il video automaticamente",
    "v_cauto"     => "Inizia il video dopo clicando qui",
    "v_size"      => "Video Size",
    "v_rsize"     => "Player modalità regolare",
    "v_tsize"     => "Player modalità teatro",
    "v_cust"      => "Modifica il Player",
    "v_butt"      => "Colore dei bottoni",
    "v_back"      => "Colore dello sfondo",
    "save_change" => "Salva modifiche",

    "modules"     => "Moduli",
    "feed"        => "Feed",

    "modsettings" => "Seleziona i moduli che vuoi apparire nella tua homepage",
    "m_mostview"  => "I più visti",
    "m_inbox"     => "Posta in arrivo",
    "m_stats"     => "Statistiche del canale",

    "subsettings" => "Impostazioni delle iscrizioni",
    "s_num"       => "Number of Rows",
    "s_from"      => "Vedi i video da:",
    "s_everyone"  => "chiunque",

    "in"          => "in",
    "all_cats"    => "All Categories",
    "v_newest"    => "Newest",
    "v_most_view" => "Most Viewed",
    "v_most_disc" => "Most Discussed",
    "v_top_rate"  => "Top Rated",

    "no_videos"   => "Nessun video trovato",

    "today"       => "Oggi",
    "this_week"   => "Questa settimana",
    "this_month"  => "Questo mese",
    "all_time"    => "sempre",
];
