<?php
return [
    "decimal_point"         => ".",
    "thousand_seperator"    => ",",

// HOMEPAGE
    "h_home"      => "Strona główna",
    "h_videos"    => "Filmy",
    "h_channels"  => "Kanały",
    "h_community" => "Społeczność",
    "h_search"    => "Szukaj",
    "h_signup"    => "Załóż konto",
    "h_signin"    => "Zaloguj się",
    "h_or"        => "albo",
    "h_subs"      => "Subskrypcje",
    "h_history"   => "Historia",
    "h_upload"    => "Wrzuć",
    "w_watched"   => "Ostatnio obejrzane filmy",
    "w_recommend" => "Rekomendowane filmy",
    "w_subscrib"  => "Subskrypcje",
    "w_featured"  => "Promowane filmy ",
    "w_popular"   => "Najbardziej popularne filmy",
    "s_customize" => "Chcesz dostosować tę stronę główną?",
    "s_si_su"     => "<a href='/signin'>Zaloguj się</a> albo <a href='/signup'>Załóż konto</a> teraz!",
    "contest"     => "Konkurs filmowy",
    "contest_prm" => "Zrób film, wrzuć go i udostępnij!",
    "contest_th"  => "Aktualny temat:",
    "contest_ent" => "<a href='/upload?e=c'>Dołącz teraz</a> | <a href='/contest'>Zobacz uczestników</a>",
    "view"        => "wyświetlenie",
    "views"       => "wyświetleń",
    "whatsnew"    => "Co nowego?",
    "delvid"      => "Usunięty film",
    "prvvid"      => "Prywatny film",
    "prtn"        => "Jest partnerem",
    "vrfd"        => "Zweryfikowany",
    "lastonline"  => "Ostatni użytkownicy online", // Why I didn't add [num]? There is no Polish substitute for this sentence (at least I think so) ~ vistafan12
    "l_videos"    => "filmów",
    "l_favs"      => "ulubionych",
    "l_friends"   => "przyjaciół",
    "langs"       => "Języki",
    "lang"        => "Język",
    "vid_pl"      => "Player",
    "layout"      => "Styl",
    "dark_mode"   => "Ciemna wersja",
    "abtvid"      => "O VidLii",
    "f_blg"       => "Blog",
    "f_about"     => "O nas",
    "f_terms"     => "Warunki korzystania",
    "f_priv"      => "Polityka prywatności",
    "f_themes"    => "Motywy",
    "hlp_inf"     => "Pomoc i informacje",
    "f_hlp_cnt"   => "Centrum pomocy",
    "f_prtner"    => "Partnerstwo",
    "f_copy"      => "Prawa autorskie",
    "f_comm"      => "Wytyczne dla społeczności",
    "you_acc"     => "Twoje konto",
    "f_vids"      => "Twoje filmy",
    "f_favs"      => "Twoje ulubione filmy",
    "f_subs"      => "Twoje subskrypcje",
    "f_acc"       => "Moje konto",
    "v_auto"      => "Autouruchamianie",
    "v_sauto"     => "Uruchom wideo automatycznie",
    "v_cauto"     => "Uruchom wideo po kliknięciu w player",
    "v_size"      => "Rozmiar wideo",
    "v_rsize"     => "Regularny rozmiar playera",
    "v_tsize"     => "Tryb kinowy playera",
    "v_cust"      => "Dostosowanie playera",
    "v_butt"      => "Kolory przycisków",
    "v_back"      => "Kolor tła",
    "save_change" => "Zapisz zmiany"
];
